### ISSUE TITLE
cannot import prroi_pool2d?

### ISSUE THREAD

**Issue by Neo-Zhangjiajie** [CSAILVision/gandissect#18]
Windows10 
cudatoolkit 9.0
python 3.6
pytorch 1.1.0
torchvision    0.3.0 

C:\Users\86189\Anaconda3\envs\py36\lib\site-packages\torch\utils\cpp_extension.py:184: UserWarning: Error checking compiler version for cl: Command 'cl' returned non-zero exit status 1.
  warnings.warn('Error checking compiler version for {}: {}'.format(compiler, error))
Traceback (most recent call last):
  File "C:\Users\86189\Anaconda3\envs\py36\lib\site-packages\torch\utils\cpp_extension.py", line 949, in _build_extension_module
    check=True)
  File "C:\Users\86189\Anaconda3\envs\py36\lib\subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\86189\Anaconda3\envs\py36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\86189\Anaconda3\envs\py36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\86189\Desktop\GANDissection\netdissect\__main__.py", line 410, in <module>
    main()
  File "C:\Users\86189\Desktop\GANDissection\netdissect\__main__.py", line 220, in main
    segrunner = GeneratorSegRunner(autoimport_eval(args.segmenter))
  File "C:\Users\86189\Desktop\GANDissection\netdissect\autoeval.py", line 36, in autoimport_eval
    return eval(term, {}, AutoImportDict())
  File "<string>", line 1, in <module>
  File "C:\Users\86189\Desktop\GANDissection\netdissect\segmenter.py", line 68, in __init__
    segarch, segvocab, epoch)
  File "C:\Users\86189\Desktop\GANDissection\netdissect\segmenter.py", line 502, in load_unified_parsing_segmentation_model
    weights=os.path.join(segmodel_dir, 'decoder_epoch_%d.pth' % epoch))
  File "C:\Users\86189\Desktop\GANDissection\netdissect\upsegmodel\models.py", line 215, in build_decoder
    fpn_dim=512)
  File "C:\Users\86189\Desktop\GANDissection\netdissect\upsegmodel\models.py", line 271, in __init__
    from .prroi_pool import PrRoIPool2D
  File "C:\Users\86189\Desktop\GANDissection\netdissect\upsegmodel\prroi_pool\__init__.py", line 12, in <module>
    from .prroi_pool import *
  File "C:\Users\86189\Desktop\GANDissection\netdissect\upsegmodel\prroi_pool\prroi_pool.py", line 14, in <module>
    from .functional import prroi_pool2d
  File "C:\Users\86189\Desktop\GANDissection\netdissect\upsegmodel\prroi_pool\functional.py", line 22, in <module>
    verbose=False
  File "C:\Users\86189\Anaconda3\envs\py36\lib\site-packages\torch\utils\cpp_extension.py", line 644, in load
    is_python_module)
  File "C:\Users\86189\Anaconda3\envs\py36\lib\site-packages\torch\utils\cpp_extension.py", line 813, in _jit_compile
    with_cuda=with_cuda)
  File "C:\Users\86189\Anaconda3\envs\py36\lib\site-packages\torch\utils\cpp_extension.py", line 866, in _write_ninja_file_and_build       
    _build_extension_module(name, build_directory, verbose)
  File "C:\Users\86189\Anaconda3\envs\py36\lib\site-packages\torch\utils\cpp_extension.py", line 962, in _build_extension_module
    raise RuntimeError(message)
RuntimeError: Error building extension '_prroi_pooling': b'[1/3] cl /showIncludes -DTORCH_EXTENSION_NAME=_prroi_pooling -DTORCH_API_INCLUDE_EXTENSION_H -IC:\\Users\\86189\\Anaconda3\\envs\\py36\\lib\\site-packages\\torch\\include -IC:\\Users\\86189\\Anaconda3\\envs\\py36\\lib\\site-packages\\torch\\include\\torch\\csrc\\api\\include -IC:\\Users\\86189\\Anaconda3\\envs\\py36\\lib\\site-packages\\torch\\include\\TH 
-IC:\\Users\\86189\\Anaconda3\\envs\\py36\\lib\\site-packages\\torch\\include\\THC "-IC:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.1\\include" -IC:\\Users\\86189\\Anaconda3\\envs\\py36\\Include -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++11 -c C:\\Users\\86189\\Desktop\\GANDissection\\netdissect\\upsegmodel\\prroi_pool\\src\\prroi_pooling_gpu.c /Foprroi_pooling_gpu.o\r\nFAILED: prroi_pooling_gpu.o \r\ncl /showIncludes -DTORCH_EXTENSION_NAME=_prroi_pooling -DTORCH_API_INCLUDE_EXTENSION_H -IC:\\Users\\86189\\Anaconda3\\envs\\py36\\lib\\site-packages\\torch\\include -IC:\\Users\\86189\\Anaconda3\\envs\\py36\\lib\\site-packages\\torch\\include\\torch\\csrc\\api\\include -IC:\\Users\\86189\\Anaconda3\\envs\\py36\\lib\\site-packages\\torch\\include\\TH -IC:\\Users\\86189\\Anaconda3\\envs\\py36\\lib\\site-packages\\torch\\include\\THC "-IC:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.1\\include" -IC:\\Users\\86189\\Anaconda3\\envs\\py36\\Include -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++11 -c C:\\Users\\86189\\Desktop\\GANDissection\\netdissect\\upsegmodel\\prroi_pool\\src\\prroi_pooling_gpu.c /Foprroi_pooling_gpu.o\r\nTraceback (most recent call last):\n  File "c:\\users\\86189\\anaconda3\\envs\\pytorch\\lib\\runpy.py", line 193, in _run_module_as_main\n    "__main__", mod_spec)\n  File "c:\\users\\86189\\anaconda3\\envs\\pytorch\\lib\\runpy.py", line 
85, in _run_code\n    exec(code, run_globals)\n  File "C:\\Users\\86189\\Anaconda3\\envs\\pytorch\\Scripts\\cl.exe\\__main__.py", line 4, in <module>\n  File "c:\\users\\86189\\anaconda3\\envs\\pytorch\\lib\\site-packages\\cl\\bin\\cl.py", line 5, in <module>\n    from kombu import Connection\n  File "c:\\users\\86189\\anaconda3\\envs\\pytorch\\lib\\site-packages\\kombu\\__init__.py", line 81, in __getattr__\n    
module = __import__(object_origins[name], None, None, [name])\n  File "c:\\users\\86189\\anaconda3\\envs\\pytorch\\lib\\site-packages\\kombu\\connection.py", line 23, in <module>\n    from kombu import exceptions\n  File "c:\\users\\86189\\anaconda3\\envs\\pytorch\\lib\\site-packages\\kombu\\exceptions.py", line 6, in <module>\n    from amqp import ChannelError, ConnectionError, ResourceError\n  File "c:\\users\\86189\\anaconda3\\envs\\pytorch\\lib\\site-packages\\amqp\\__init__.py", line 33, in <module>\n    from .connection import Connection  # noqa\n  File "c:\\users\\86189\\anaconda3\\envs\\pytorch\\lib\\site-packages\\amqp\\connection.py", line 21, in <module>\n    from .transport 
import Transport\n  File "c:\\users\\86189\\anaconda3\\envs\\pytorch\\lib\\site-packages\\amqp\\transport.py", line 8, in <module>\n    import ssl\n  File "c:\\users\\86189\\anaconda3\\envs\\pytorch\\lib\\ssl.py", line 98, in <module>\n    import _ssl             # if we can\'t import it, let the error propagate\nImportError: DLL load failed: \xd5\xd2\xb2\xbb\xb5\xbd\xd6\xb8\xb6\xa8\xb5\xc4\xc4\xa3\xbf\xe9\xa1\xa3\n[2/3] C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.1\\bin\\nvcc -DTORCH_EXTENSION_NAME=_prroi_pooling -DTORCH_API_INCLUDE_EXTENSION_H -IC:\\Users\\86189\\Anaconda3\\envs\\py36\\lib\\site-packages\\torch\\include -IC:\\Users\\86189\\Anaconda3\\envs\\py36\\lib\\site-packages\\torch\\include\\torch\\csrc\\api\\include -IC:\\Users\\86189\\Anaconda3\\envs\\py36\\lib\\site-packages\\torch\\include\\TH -IC:\\Users\\86189\\Anaconda3\\envs\\py36\\lib\\site-packages\\torch\\include\\THC "-IC:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.1\\include" -IC:\\Users\\86189\\Anaconda3\\envs\\py36\\Include -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -c C:\\Users\\86189\\Desktop\\GANDissection\\netdissect\\upsegmodel\\prroi_pool\\src\\prroi_pooling_gpu_impl.cu -o prroi_pooling_gpu_impl.cuda.o\r\nFAILED: prroi_pooling_gpu_impl.cuda.o \r\nC:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.1\\bin\\nvcc -DTORCH_EXTENSION_NAME=_prroi_pooling -DTORCH_API_INCLUDE_EXTENSION_H -IC:\\Users\\86189\\Anaconda3\\envs\\py36\\lib\\site-packages\\torch\\include -IC:\\Users\\86189\\Anaconda3\\envs\\py36\\lib\\site-packages\\torch\\include\\torch\\csrc\\api\\include -IC:\\Users\\86189\\Anaconda3\\envs\\py36\\lib\\site-packages\\torch\\include\\TH -IC:\\Users\\86189\\Anaconda3\\envs\\py36\\lib\\site-packages\\torch\\include\\THC "-IC:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.1\\include" -IC:\\Users\\86189\\Anaconda3\\envs\\py36\\Include -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -c C:\\Users\\86189\\Desktop\\GANDissection\\netdissect\\upsegmodel\\prroi_pool\\src\\prroi_pooling_gpu_impl.cu -o prroi_pooling_gpu_impl.cuda.o\r\nTraceback (most recent call last):\r\n  File "c:\\users\\86189\\anaconda3\\envs\\pytorch\\lib\\runpy.py", line 193, in _run_module_as_main\r\n    "__main__", mod_spec)\r\n  File "c:\\users\\86189\\anaconda3\\envs\\pytorch\\lib\\runpy.py", line 85, in _run_code\r\n    exec(code, run_globals)\r\n  File "C:\\Users\\86189\\Anaconda3\\envs\\pytorch\\Scripts\\cl.exe\\__main__.py", line 4, in <module>\r\n  File "c:\\users\\86189\\anaconda3\\envs\\pytorch\\lib\\site-packages\\cl\\bin\\cl.py", line 5, in <module>\r\n    from kombu import Connection\r\n  File "c:\\users\\86189\\anaconda3\\envs\\pytorch\\lib\\site-packages\\kombu\\__init__.py", line 81, in __getattr__\r\n    module = __import__(object_origins[name], None, None, [name])\r\n  File "c:\\users\\86189\\anaconda3\\envs\\pytorch\\lib\\site-packages\\kombu\\connection.py", line 23, in <module>\r\n    from kombu import exceptions\r\n  File "c:\\users\\86189\\anaconda3\\envs\\pytorch\\lib\\site-packages\\kombu\\exceptions.py", line 6, in <module>\r\n    from amqp import ChannelError, ConnectionError, ResourceError\r\n  File "c:\\users\\86189\\anaconda3\\envs\\pytorch\\lib\\site-packages\\amqp\\__init__.py", line 33, in <module>\r\n    from .connection import Connection  # noqa\r\n  
File "c:\\users\\86189\\anaconda3\\envs\\pytorch\\lib\\site-packages\\amqp\\connection.py", line 21, in <module>\r\n    from .transport import Transport\r\n  File "c:\\users\\86189\\anaconda3\\envs\\pytorch\\lib\\site-packages\\amqp\\transport.py", line 8, in <module>\r\n    import ssl\r\n  File "c:\\users\\86189\\anaconda3\\envs\\pytorch\\lib\\ssl.py", line 98, in <module>\r\n    import _ssl             # if we can\'t import it, let the error propagate\r\nImportError: DLL load failed: \xd5\xd2\xb2\xbb\xb5\xbd\xd6\xb8\xb6\xa8\xb5\xc4\xc4\xa3\xbf\xe9\xa1\xa3\r\nninja: build stopped: subcommand failed.\r\n'

**Comment by davidbau** [comment]
For the segmenter to work, you need to be able to JIT compile pytorch
modules, which means that you need a bunch of dependencies.

The conda environment described here works for me.
https://github.com/davidbau/envs/blob/master/script/p3t14.yml
